### ISSUE TITLE
[BE] Validation ExceptionHandler가 POST 이외의 method에서도 동작해야 하지 않나요 ?

### ISSUE THREAD

**Issue by GreenNarae0** [Step3-kakao-tech-campus/Team16_BE#30]
현재 validation exception handler 에는 postmapping method를 체크하고 있는데,
path variable 또는 query parameter를 사용하는 다른 method 에서도 동작해야 한다고 생각해봤습니다.

**Comment by latteisacat** [comment]
그럼 범위를 좀 늘려보겠습니다. Get이랑 Patch도 추가해야겠네요
