### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by GreenNarae0** [Step3-kakao-tech-campus/Team16_BE#5]
SpringBoot 프로젝트를 생성합니다.
미리 약속된 기본 라이브러리들과 함께 생성합니다.

com.daggle.animory

**JDK**

OpenJDK 17

**Dependency Manager**

Gradle ≥ 7.3.1

**Framework**

SpringBoot 2.7.15

**기타 의존성**

`implementation 'org.springframework.boot:spring-boot-starter-web'`

`implementation "org.springframework.boot:spring-boot-starter-data-jpa"`

`implementation 'org.springframework.boot:spring-boot-starter-validation'`

`compileOnly 'org.projectlombok:lombok'`

`annotationProcessor 'org.projectlombok:lombok'`

`testImplementation 'org.springframework.boot:spring-boot-starter-test'`

`runtimeOnly 'com.h2database:h2'`

**Comment by latteisacat** [comment]
프로젝트 생성 완료했습니다
